version: "3.8"

services:
  backend:
    build:
      context: .                       # ← корень проекта
      dockerfile: app/backend/Dockerfile
    container_name: myproject_backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: myproject_frontend
    ports:
      - "4173:4173"
